import type { Metadata } from "next";
import { ReactNode } from "react";
import "./globals.css";
import Layout from "./components/layout/Layout";


export const metadata: Metadata = {
  title: "تک شاپ",
  description: "Generated by create next app",
};

export default function RootLayout({children}:{children:ReactNode}) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body className="font-shabnam 2xl:container mx-auto">
        <Layout>
        {children}
        </Layout>
      </body>
    </html>
  );
}
